#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive

if ! command -v git >/dev/null 2>&1; then
    apt-get update
    apt-get install -y git
fi

if ! command -v nginx >/dev/null 2>&1; then
    apt-get install -y nginx
fi